# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\angel\Desktop\Crud DB\GUI Crud Ok\interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1228, 887)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/*background-color: rgb(255, 255, 255);*/\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fr_contenedor = QtWidgets.QFrame(self.centralwidget)
        self.fr_contenedor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fr_contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_contenedor.setObjectName("fr_contenedor")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fr_contenedor)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr_superior = QtWidgets.QFrame(self.fr_contenedor)
        self.fr_superior.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_superior.setStyleSheet("*{background-color:#DEC085 ;}   /*#f39c12*/\n"
"\n"
"/* Estilo para el botón de cerrar */\n"
"#bt_cerrar {\n"
"    padding: 10px;\n"
"    background-color: #e74c3c; /* Color rojo */\n"
"    border: 2px solid #c0392b; /* Borde rojo oscuro */\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"    color: #fff; /* Color del texto */\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s; /* Transición de color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"/* Estilo para el botón de minimizar */\n"
"#bt_minimizar {\n"
"    padding: 10px;\n"
"    background-color: #3498db; /* Color azul */\n"
"    border: 2px solid #2980b9; /* Borde azul oscuro */\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"    margin-right: 2.5px;\n"
"    color: #fff; /* Color del texto */\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s; /* Transición de color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"/* Estilo para el botón de maximizar */\n"
"#bt_maximizar {\n"
"    padding: 10px;\n"
"    background-color: #3498db; /* Color azul */\n"
"    border: 2px solid #2980b9; /* Borde azul oscuro */\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px; /* Margen en la parte inferior */\n"
"    margin-right: 2.5px;\n"
"    color: #fff; /* Color del texto */\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s; /* Transición de color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"/* Efecto hover para todos los botones */\n"
"#bt_cerrar:hover,\n"
"#bt_minimizar:hover,\n"
"#bt_maximizar:hover {\n"
"    background-color: #c0392b; /* Cambio de color de fondo al pasar el mouse para el botón de cerrar */\n"
"}\n"
"\n"
"#bt_minimizar:hover,\n"
"#bt_maximizar:hover {\n"
"    background-color: #2980b9; /* Cambio de color de fondo al pasar el mouse para los botones de minimizar y maximizar */\n"
"}\n"
"\n"
"\n"
"")
        self.fr_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_superior.setObjectName("fr_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fr_superior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.fr_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(self.fr_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 0))
        self.bt_minimizar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bt_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimizar.setIcon(icon)
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout_2.addWidget(self.bt_minimizar)
        self.bt_maximizar = QtWidgets.QPushButton(self.fr_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 0))
        self.bt_maximizar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bt_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_maximizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/maximize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximizar.setIcon(icon1)
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout_2.addWidget(self.bt_maximizar)
        self.bt_cerrar = QtWidgets.QPushButton(self.fr_superior)
        self.bt_cerrar.setMinimumSize(QtCore.QSize(40, 0))
        self.bt_cerrar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bt_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cerrar.setStyleSheet("bt_cerrar {\n"
"    padding: 10px;\n"
"    background-color: #e74c3c; /* Color rojo */\n"
"    border: 2px solid #c0392b; /* Borde rojo oscuro */\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"    color: #fff; /* Color del texto */\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s; /* Transición de color de fondo al pasar el mouse */\n"
"}")
        self.bt_cerrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar.setIcon(icon2)
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout_2.addWidget(self.bt_cerrar)
        self.verticalLayout.addWidget(self.fr_superior)
        self.fr_main = QtWidgets.QFrame(self.fr_contenedor)
        self.fr_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_main.setObjectName("fr_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_main)
        self.verticalLayout_2.setContentsMargins(7, 0, 0, 7)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fr_menu_titulo = QtWidgets.QFrame(self.fr_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.fr_menu_titulo.sizePolicy().hasHeightForWidth())
        self.fr_menu_titulo.setSizePolicy(sizePolicy)
        self.fr_menu_titulo.setMinimumSize(QtCore.QSize(0, 0))
        self.fr_menu_titulo.setMaximumSize(QtCore.QSize(16777215, 60))
        self.fr_menu_titulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_menu_titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_menu_titulo.setObjectName("fr_menu_titulo")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fr_menu_titulo)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bt_menu = QtWidgets.QPushButton(self.fr_menu_titulo)
        self.bt_menu.setMinimumSize(QtCore.QSize(275, 40))
        self.bt_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_menu.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu.setIcon(icon3)
        self.bt_menu.setIconSize(QtCore.QSize(40, 40))
        self.bt_menu.setObjectName("bt_menu")
        self.horizontalLayout_4.addWidget(self.bt_menu)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.fr_menu_titulo)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.fr_menu_titulo)
        self.frame_2 = QtWidgets.QFrame(self.fr_main)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fr_menu = QtWidgets.QFrame(self.frame_2)
        self.fr_menu.setMinimumSize(QtCore.QSize(300, 0))
        self.fr_menu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.fr_menu.setStyleSheet("QPushButton{\n"
"    padding: 10px;\n"
"    background-color: #DEC085;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"    font-size: 18px;\n"
"    text-align: left; \n"
"    padding-left: 60px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white; /* Fondo gris claro cuando el mouse está sobre el botón */\n"
"    color: black; /* Texto en color negro cuando el mouse está sobre el botón */\n"
"}\n"
"\n"
"#fr_menu {\n"
"    background-color: ;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 20px;\n"
"    margin-right: 5px;\n"
"}")
        self.fr_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_menu.setObjectName("fr_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fr_menu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bt_exposicion = QtWidgets.QPushButton(self.fr_menu)
        self.bt_exposicion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_exposicion.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/table.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_exposicion.setIcon(icon4)
        self.bt_exposicion.setCheckable(False)
        self.bt_exposicion.setAutoRepeat(False)
        self.bt_exposicion.setObjectName("bt_exposicion")
        self.verticalLayout_3.addWidget(self.bt_exposicion)
        self.bt_obra = QtWidgets.QPushButton(self.fr_menu)
        self.bt_obra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_obra.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_obra.setIcon(icon4)
        self.bt_obra.setCheckable(False)
        self.bt_obra.setAutoRepeat(False)
        self.bt_obra.setObjectName("bt_obra")
        self.verticalLayout_3.addWidget(self.bt_obra)
        self.bt_artista = QtWidgets.QPushButton(self.fr_menu)
        self.bt_artista.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_artista.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_artista.setIcon(icon4)
        self.bt_artista.setCheckable(False)
        self.bt_artista.setAutoRepeat(False)
        self.bt_artista.setObjectName("bt_artista")
        self.verticalLayout_3.addWidget(self.bt_artista)
        self.bt_telefono = QtWidgets.QPushButton(self.fr_menu)
        self.bt_telefono.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_telefono.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_telefono.setIcon(icon4)
        self.bt_telefono.setCheckable(False)
        self.bt_telefono.setAutoRepeat(False)
        self.bt_telefono.setObjectName("bt_telefono")
        self.verticalLayout_3.addWidget(self.bt_telefono)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.bt_tablas = QtWidgets.QPushButton(self.fr_menu)
        self.bt_tablas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_tablas.setIcon(icon5)
        self.bt_tablas.setObjectName("bt_tablas")
        self.verticalLayout_3.addWidget(self.bt_tablas)
        self.bt_obra_vendida = QtWidgets.QPushButton(self.fr_menu)
        self.bt_obra_vendida.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/shopping-cart.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_obra_vendida.setIcon(icon6)
        self.bt_obra_vendida.setCheckable(False)
        self.bt_obra_vendida.setObjectName("bt_obra_vendida")
        self.verticalLayout_3.addWidget(self.bt_obra_vendida)
        self.bt_acerca_de = QtWidgets.QPushButton(self.fr_menu)
        self.bt_acerca_de.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_acerca_de.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_acerca_de.setIcon(icon7)
        self.bt_acerca_de.setCheckable(False)
        self.bt_acerca_de.setAutoRepeat(False)
        self.bt_acerca_de.setObjectName("bt_acerca_de")
        self.verticalLayout_3.addWidget(self.bt_acerca_de)
        self.horizontalLayout_3.addWidget(self.fr_menu)
        self.fr_tablas = QtWidgets.QFrame(self.frame_2)
        self.fr_tablas.setStyleSheet("#fr_tablas {\n"
"    background-color: ;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 20px;\n"
"    margin-right: 5px;\n"
"}")
        self.fr_tablas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_tablas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_tablas.setObjectName("fr_tablas")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fr_tablas)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.fr_tablas)
        self.stackedWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: #DEC085;\n"
"    font-size: 20px;\n"
"}\n"
"{\n"
"background-color: ;\n"
"border: 1px solid #3498db;\n"
"font-size: 30px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_tb = QtWidgets.QWidget()
        self.page_tb.setObjectName("page_tb")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_tb)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fr_nombre_tb = QtWidgets.QFrame(self.page_tb)
        self.fr_nombre_tb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_nombre_tb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_nombre_tb.setObjectName("fr_nombre_tb")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fr_nombre_tb)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_tabla = QtWidgets.QLabel(self.fr_nombre_tb)
        self.lb_tabla.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lb_tabla.setFont(font)
        self.lb_tabla.setObjectName("lb_tabla")
        self.horizontalLayout_5.addWidget(self.lb_tabla)
        self.lb_nombre_tb = QtWidgets.QLabel(self.fr_nombre_tb)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(16)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lb_nombre_tb.setFont(font)
        self.lb_nombre_tb.setText("")
        self.lb_nombre_tb.setObjectName("lb_nombre_tb")
        self.horizontalLayout_5.addWidget(self.lb_nombre_tb)
        self.verticalLayout_5.addWidget(self.fr_nombre_tb)
        self.tb_main = QtWidgets.QTableWidget(self.page_tb)
        self.tb_main.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tb_main.setObjectName("tb_main")
        self.tb_main.setColumnCount(0)
        self.tb_main.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tb_main)
        self.stackedWidget.addWidget(self.page_tb)
        self.page_acerca_de = QtWidgets.QWidget()
        self.page_acerca_de.setObjectName("page_acerca_de")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_acerca_de)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.text_acerca_de = QtWidgets.QTextBrowser(self.page_acerca_de)
        self.text_acerca_de.setObjectName("text_acerca_de")
        self.verticalLayout_6.addWidget(self.text_acerca_de)
        self.stackedWidget.addWidget(self.page_acerca_de)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_obras_vendidas = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lb_obras_vendidas.setFont(font)
        self.lb_obras_vendidas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_obras_vendidas.setObjectName("lb_obras_vendidas")
        self.horizontalLayout.addWidget(self.lb_obras_vendidas)
        self.cb_exposicion = QtWidgets.QComboBox(self.frame)
        self.cb_exposicion.setMinimumSize(QtCore.QSize(300, 0))
        self.cb_exposicion.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(15)
        self.cb_exposicion.setFont(font)
        self.cb_exposicion.setObjectName("cb_exposicion")
        self.cb_exposicion.addItem("")
        self.cb_exposicion.addItem("")
        self.cb_exposicion.addItem("")
        self.horizontalLayout.addWidget(self.cb_exposicion)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_8.addWidget(self.frame)
        self.tb_vendido = QtWidgets.QTableWidget(self.page)
        self.tb_vendido.setObjectName("tb_vendido")
        self.tb_vendido.setColumnCount(0)
        self.tb_vendido.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tb_vendido)
        self.stackedWidget.addWidget(self.page)
        self.page_blanco = QtWidgets.QWidget()
        self.page_blanco.setMaximumSize(QtCore.QSize(817, 626))
        self.page_blanco.setObjectName("page_blanco")
        self.stackedWidget.addWidget(self.page_blanco)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.fr_crud = QtWidgets.QFrame(self.fr_tablas)
        self.fr_crud.setMinimumSize(QtCore.QSize(0, 100))
        self.fr_crud.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fr_crud.setStyleSheet("/* Estilo para el botón Agregar */\n"
"\n"
"QPushButton {width: 100px; height: 25px;}\n"
"\n"
"#bt_agregar {\n"
"    padding: 15px 30px;\n"
"    background-color: #2ecc71; /* Color verde */\n"
"    border: 2px solid #27ae60; /* Borde verde oscuro */\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px; /* Margen en la parte inferior */\n"
"    margin-right: 5px; /* Margen en la parte derecha */\n"
"    color: #fff; /* Color del texto */\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s; /* Transición de color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"/* Estilo para el botón Editar */\n"
"#bt_editar {\n"
"    padding: 15px 30px;\n"
"    background-color: #3498db; /* Color azul */\n"
"    border: 2px solid #2980b9; /* Borde azul oscuro */\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px; /* Margen en la parte inferior */\n"
"    margin-right: 5px; /* Margen en la parte derecha */\n"
"    color: #fff; /* Color del texto */\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s; /* Transición de color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"/* Estilo para el botón Eliminar */\n"
"#bt_eliminar {\n"
"    padding: 15px 30px;\n"
"    background-color: #e74c3c; /* Color rojo */\n"
"    border: 2px solid #c0392b; /* Borde rojo oscuro */\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px; /* Margen en la parte inferior */\n"
"    margin-right: 10px; /* Margen en la parte derecha */\n"
"    color: #fff; /* Color del texto */\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s; /* Transición de color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"/* Estilo para el botón Actualizar */\n"
"#bt_actualizar {\n"
"    padding: 15px 30px;\n"
"    background-color: #f39c12; /* Color naranja */\n"
"    border: 2px solid #27ae60; /* Borde verde oscuro */\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px; /* Margen en la parte inferior */\n"
"    margin-right: 10px; /* Margen en la parte derecha */\n"
"    color: #fff; /* Color del texto */\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s; /* Transición de color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"#bt_agregar {\n"
"    background-color: #2ecc71; /* Color verde */\n"
"}\n"
"\n"
"/* Efecto hover para el botón Agregar */\n"
"#bt_agregar:hover {\n"
"    background-color: #27ae60; /* Cambio de color de fondo al pasar el mouse */\n"
"    transform: scale(1.1); /* Escala del botón al pasar el mouse */\n"
"}\n"
"\n"
"/* Estilo para el botón Editar */\n"
"#bt_editar {\n"
"    background-color: #3498db; /* Color azul */\n"
"}\n"
"\n"
"/* Efecto hover para el botón Editar */\n"
"#bt_editar:hover {\n"
"    background-color: #2980b9; /* Cambio de color de fondo al pasar el mouse */\n"
"    transform: scale(1.1); /* Escala del botón al pasar el mouse */\n"
"}\n"
"\n"
"/* Estilo para el botón Eliminar */\n"
"#bt_eliminar {\n"
"    background-color: #e74c3c; /* Color rojo */\n"
"}\n"
"\n"
"/* Efecto hover para el botón Eliminar */\n"
"#bt_eliminar:hover {\n"
"    background-color: #c0392b; /* Cambio de color de fondo al pasar el mouse */\n"
"    transform: scale(1.1); /* Escala del botón al pasar el mouse */\n"
"}\n"
"\n"
"/* Estilo para el botón Actualizar */\n"
"#bt_actualizar {\n"
"    background-color: #2ecc71; /* Color naranja */\n"
"}\n"
"\n"
"/* Efecto hover para el botón Actualizar */\n"
"#bt_actualizar:hover {\n"
"    background-color:#27ae60; /* Cambio de color de fondo al pasar el mouse */\n"
"    transform: scale(1.1); /* Escala del botón al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-size:18px ;\n"
"}")
        self.fr_crud.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_crud.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_crud.setObjectName("fr_crud")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fr_crud)
        self.horizontalLayout_6.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bt_agregar = QtWidgets.QPushButton(self.fr_crud)
        self.bt_agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_agregar.setIcon(icon8)
        self.bt_agregar.setObjectName("bt_agregar")
        self.horizontalLayout_6.addWidget(self.bt_agregar)
        self.bt_editar = QtWidgets.QPushButton(self.fr_crud)
        self.bt_editar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_editar.setIcon(icon9)
        self.bt_editar.setObjectName("bt_editar")
        self.horizontalLayout_6.addWidget(self.bt_editar)
        self.bt_eliminar = QtWidgets.QPushButton(self.fr_crud)
        self.bt_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/trash-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_eliminar.setIcon(icon10)
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.horizontalLayout_6.addWidget(self.bt_eliminar)
        spacerItem5 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.bt_actualizar = QtWidgets.QPushButton(self.fr_crud)
        self.bt_actualizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/check-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_actualizar.setIcon(icon11)
        self.bt_actualizar.setObjectName("bt_actualizar")
        self.horizontalLayout_6.addWidget(self.bt_actualizar)
        self.verticalLayout_4.addWidget(self.fr_crud)
        self.horizontalLayout_3.addWidget(self.fr_tablas)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.fr_main)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout_7.addWidget(self.fr_contenedor)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "  Galería bd"))
        self.label_2.setText(_translate("MainWindow", "Base de Datos"))
        self.bt_exposicion.setText(_translate("MainWindow", "Exposición"))
        self.bt_obra.setText(_translate("MainWindow", "Obra"))
        self.bt_artista.setText(_translate("MainWindow", "Artista"))
        self.bt_telefono.setText(_translate("MainWindow", "Teléfono"))
        self.bt_tablas.setText(_translate("MainWindow", "Base de Datos"))
        self.bt_obra_vendida.setText(_translate("MainWindow", "Obras Vendidas"))
        self.bt_acerca_de.setText(_translate("MainWindow", "Acerca de..."))
        self.lb_tabla.setText(_translate("MainWindow", "Tabla:"))
        self.text_acerca_de.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Acerca de la aplicación:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; text-decoration: underline;\">Desarrolladores:</span><span style=\" font-size:10pt;\"> Angel Gabriel Garcia Plutin</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">                          Javier Alexey Molina Cardoso</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; text-decoration: underline;\">Descripción:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Sistema de información para galería de arte que proporciona acceso actualizado a exposiciones, incluyendo detalles como título, descripción, fechas de inauguración y clausura. La aplicación muestra obras de arte con información detallada como título, artista, estilo y precio de salida. Permite a los usuarios realizar ofertas por obras, y al finalizar la exposición, el propietario puede vender la obra al mejor postor. Desarrollado en Python, la aplicación utiliza la biblioteca PyQt5 para construir la interfaz gráfica de usuario. Para diseñar visualmente la interfaz, se empleó Qt Designer, una herramienta que facilita la creación de interfaces gráficas mediante la disposición de widgets de manera intuitiva. La gestión de la base de datos se lleva a cabo con sqlite3, garantizando la eficiente manipulación de la información. Visual Studio Code 1.81.0 fue el entorno de desarrollo utilizado para escribir y organizar el código, mientras que DB Browser SQLite 3.12.2 permitió explorar y administrar eficientemente la base de datos. La aplicación se basa en un Modelo Entidad Relación (MER) y un modelo relacional para implementar el sistema de información de la galería de arte.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Versión</span><span style=\" font-size:10pt; font-weight:600;\">: 1.0</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; vertical-align:super;\"><br /></span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lb_obras_vendidas.setText(_translate("MainWindow", "Obras vendidas en la exposición:"))
        self.cb_exposicion.setItemText(0, _translate("MainWindow", "New Item"))
        self.cb_exposicion.setItemText(1, _translate("MainWindow", "New Item"))
        self.cb_exposicion.setItemText(2, _translate("MainWindow", "New Item"))
        self.bt_agregar.setText(_translate("MainWindow", "Agregar"))
        self.bt_editar.setText(_translate("MainWindow", "Editar"))
        self.bt_eliminar.setText(_translate("MainWindow", "Eliminar"))
        self.bt_actualizar.setText(_translate("MainWindow", "Actualizar"))
import icons_rc
