# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\angel\Desktop\Crud DB\GUI Crud Ok\interfaz_eliminar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(359, 231)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("#frame{\n"
"    background-color: #DEC085 ;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 15px;\n"
"    margin-right: 4px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.cb_tablas = QtWidgets.QComboBox(self.frame)
        self.cb_tablas.setObjectName("cb_tablas")
        self.cb_tablas.addItem("")
        self.cb_tablas.setItemText(0, "")
        self.cb_tablas.addItem("")
        self.cb_tablas.addItem("")
        self.cb_tablas.addItem("")
        self.cb_tablas.addItem("")
        self.verticalLayout_2.addWidget(self.cb_tablas)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_id = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.verticalLayout_2.addWidget(self.lineEdit_id)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bt_aceptar = QtWidgets.QPushButton(Dialog)
        self.bt_aceptar.setObjectName("bt_aceptar")
        self.horizontalLayout.addWidget(self.bt_aceptar)
        self.bt_cancelar = QtWidgets.QPushButton(Dialog)
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.horizontalLayout.addWidget(self.bt_cancelar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Tablas"))
        self.cb_tablas.setItemText(1, _translate("Dialog", "Exposición"))
        self.cb_tablas.setItemText(2, _translate("Dialog", "Artista"))
        self.cb_tablas.setItemText(3, _translate("Dialog", "Obra"))
        self.cb_tablas.setItemText(4, _translate("Dialog", "Teléfono"))
        self.label_2.setText(_translate("Dialog", "Entre ID del elemento a eliminar:"))
        self.bt_aceptar.setText(_translate("Dialog", "Aceptar"))
        self.bt_cancelar.setText(_translate("Dialog", "Cancelar"))
